### ISSUE TITLE
Ghost cursers with chatter-smooth

### ISSUE THREAD

**Issue by C0D3-M4513R** [Kuuuube/Kuuube-s-CHATTER-EXTERMINATOR#3]
item | value
--|--
Frequency | 1000
Chatter extermination strength | 6 and 15
plugin version | 1.0.1.0
otd | 0.6.0.4
tablet | MTE-450

This only happens, when using the smooth variant. It does not affect the raw filter.

I am experiencing consistent curser teleportation to two very different spots (and three in total). I can get the cursor to teleport to a fixed posision, a position in between the fixed and "real" position and the "real" position. It doesn't matter where on the tablet or screen I am. The affecting factor seems to be height. I hover a certain range away from the tablet, and my cursor starts teleporting.
I recorded my tablet input using otd's tablet debugger.
To debug this, you are welcome to message/dm me (@ C0D3 M4513R) on discord. I am also part of the otd server.

[tablet-data.txt](https://github.com/Kuuuube/Kuuube-s-CHATTER-EXTERMINATOR/files/9212699/tablet-data.txt)

**Comment by Kuuuube** [comment]
This appears to be an issue with this tablet and not the plugin. I'm not sure why the raw version works and the smooth one doesn't.

While investigating this I found that this tablet reports NearProximity but OTD is not parsing it so I've made a PR for that on the OTD repo. [#2366](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2366)

When this gets merged or if you grab the actions build for it, you can use [Hover Distance Limiter](https://github.com/Kuuuube/Hover_Distance_Limiter) with `Use Near Proximity Cutoff` enabled or set a range that removes the reports at the very top of hover to filter out these reports.

**Comment by C0D3-M4513R** [comment]
The intresting thing is, that in otd the cursor shows up correctly.
With and without the plugin.
The parsed data otd wise in the tablet debugger also seems to be fine. I even looked at the raw bytes.
Whilst getting to the tablet the reports go from 02 50 to 02 D0 to 02 90 (farthest to closest) (refer OpenTabletDriver/OpenTabletDriver#656).
For the first two, the cursor teleporting happens. For the last it doesn't.

During all of those reports the cursor was jumping on screen, but almost steady (normal holding shake) in otd.
[tablet-data.txt](https://github.com/Kuuuube/Kuuube-s-CHATTER-EXTERMINATOR/files/9213502/tablet-data.txt)

**Comment by C0D3-M4513R** [comment]
> This appears to be an issue with this tablet

Since when do plugins operate on raw tablet values?
Either the tablet is either actually reporting three different far away values (which it is not, since that would show in the debugger, right?)
Or this is a OTD parsing issue (but otd works fine without the plugin.).

So what is different about my tablet, only if I add your interpolator?
